var hierarchy =
[
    [ "_G", "class___g.html", null ],
    [ "any", "classany.html", null ],
    [ "boolean", "classboolean.html", null ],
    [ "THlib::boss::card", "class_t_hlib_1_1boss_1_1card.html", null ],
    [ "lstg::Color", "classlstg_1_1_color.html", null ],
    [ "THlib::boss::dialog", "class_t_hlib_1_1boss_1_1dialog.html", null ],
    [ "THlib::boss::escape", "class_t_hlib_1_1boss_1_1escape.html", null ],
    [ "THlib::archimedes::expand", "class_t_hlib_1_1archimedes_1_1expand.html", null ],
    [ "THlib::ext", "class_t_hlib_1_1ext.html", null ],
    [ "function", "classfunction.html", null ],
    [ "THlib::stage::group", "class_t_hlib_1_1stage_1_1group.html", null ],
    [ "THlib::Heap", "class_t_hlib_1_1_heap.html", null ],
    [ "THlib::List", "class_t_hlib_1_1_list.html", null ],
    [ "local", "classlocal.html", null ],
    [ "THlib::menu", "class_t_hlib_1_1menu.html", null ],
    [ "THlib::misc", "class_t_hlib_1_1misc.html", null ],
    [ "THlib::boss::move", "class_t_hlib_1_1boss_1_1move.html", null ],
    [ "THlib::music_list", "class_t_hlib_1_1music__list.html", null ],
    [ "nil", "classnil.html", null ],
    [ "number", "classnumber.html", null ],
    [ "object", "classobject.html", [
      [ "THlib::_bullet_shooter", "class_t_hlib_1_1__bullet__shooter.html", null ],
      [ "THlib::_object", "class_t_hlib_1_1__object.html", null ],
      [ "THlib::background", "class_t_hlib_1_1background.html", null ],
      [ "THlib::bomb_bullet_killer", "class_t_hlib_1_1bomb__bullet__killer.html", null ],
      [ "THlib::boss_cast_ef", "class_t_hlib_1_1boss__cast__ef.html", null ],
      [ "THlib::boss_cast_ef_unit", "class_t_hlib_1_1boss__cast__ef__unit.html", null ],
      [ "THlib::boss_death_ef", "class_t_hlib_1_1boss__death__ef.html", null ],
      [ "THlib::boss_death_ef_unit", "class_t_hlib_1_1boss__death__ef__unit.html", null ],
      [ "THlib::boss_ui", "class_t_hlib_1_1boss__ui.html", null ],
      [ "THlib::bubble", "class_t_hlib_1_1bubble.html", null ],
      [ "THlib::bubble2", "class_t_hlib_1_1bubble2.html", null ],
      [ "THlib::bubble3", "class_t_hlib_1_1bubble3.html", null ],
      [ "THlib::bullet", "class_t_hlib_1_1bullet.html", [
        [ "THlib::_straight", "class_t_hlib_1_1__straight.html", null ],
        [ "THlib::archiexpand", "class_t_hlib_1_1archiexpand.html", null ],
        [ "THlib::archirotate", "class_t_hlib_1_1archirotate.html", null ],
        [ "THlib::shooter", "class_t_hlib_1_1shooter.html", null ],
        [ "THlib::straight", "class_t_hlib_1_1straight.html", null ],
        [ "THlib::straight_495", "class_t_hlib_1_1straight__495.html", null ],
        [ "THlib::straight_indes", "class_t_hlib_1_1straight__indes.html", null ]
      ] ],
      [ "THlib::bullet_cleaner", "class_t_hlib_1_1bullet__cleaner.html", null ],
      [ "THlib::bullet_deleter", "class_t_hlib_1_1bullet__deleter.html", null ],
      [ "THlib::bullet_deleter2", "class_t_hlib_1_1bullet__deleter2.html", null ],
      [ "THlib::bullet_killer", "class_t_hlib_1_1bullet__killer.html", null ],
      [ "THlib::bullet_killer_SP", "class_t_hlib_1_1bullet__killer___s_p.html", null ],
      [ "THlib::BulletBreak", "class_t_hlib_1_1_bullet_break.html", null ],
      [ "THlib::camera_setter", "class_t_hlib_1_1camera__setter.html", null ],
      [ "THlib::deatheff", "class_t_hlib_1_1deatheff.html", null ],
      [ "THlib::dialog_displayer", "class_t_hlib_1_1dialog__displayer.html", null ],
      [ "THlib::diff_render_obj", "class_t_hlib_1_1diff__render__obj.html", null ],
      [ "THlib::enemy_death_ef", "class_t_hlib_1_1enemy__death__ef.html", null ],
      [ "THlib::enemybase", "class_t_hlib_1_1enemybase.html", [
        [ "THlib::boss", "class_t_hlib_1_1boss.html", null ],
        [ "THlib::enemy", "class_t_hlib_1_1enemy.html", [
          [ "THlib::EnemySimple", "class_t_hlib_1_1_enemy_simple.html", null ]
        ] ]
      ] ],
      [ "THlib::float_text", "class_t_hlib_1_1float__text.html", null ],
      [ "THlib::grazer", "class_t_hlib_1_1grazer.html", null ],
      [ "THlib::hinter", "class_t_hlib_1_1hinter.html", null ],
      [ "THlib::hinter_bonus", "class_t_hlib_1_1hinter__bonus.html", null ],
      [ "THlib::img_class", "class_t_hlib_1_1img__class.html", [
        [ "THlib::arrow_big", "class_t_hlib_1_1arrow__big.html", null ],
        [ "THlib::arrow_mid", "class_t_hlib_1_1arrow__mid.html", null ],
        [ "THlib::arrow_small", "class_t_hlib_1_1arrow__small.html", null ],
        [ "THlib::ball_big", "class_t_hlib_1_1ball__big.html", null ],
        [ "THlib::ball_huge", "class_t_hlib_1_1ball__huge.html", null ],
        [ "THlib::ball_huge_dark", "class_t_hlib_1_1ball__huge__dark.html", null ],
        [ "THlib::ball_light", "class_t_hlib_1_1ball__light.html", null ],
        [ "THlib::ball_light_dark", "class_t_hlib_1_1ball__light__dark.html", null ],
        [ "THlib::ball_mid", "class_t_hlib_1_1ball__mid.html", null ],
        [ "THlib::ball_mid_b", "class_t_hlib_1_1ball__mid__b.html", null ],
        [ "THlib::ball_mid_c", "class_t_hlib_1_1ball__mid__c.html", null ],
        [ "THlib::ball_mid_d", "class_t_hlib_1_1ball__mid__d.html", null ],
        [ "THlib::ball_small", "class_t_hlib_1_1ball__small.html", null ],
        [ "THlib::butterfly", "class_t_hlib_1_1butterfly.html", null ],
        [ "THlib::ellipse", "class_t_hlib_1_1ellipse.html", null ],
        [ "THlib::grain_a", "class_t_hlib_1_1grain__a.html", null ],
        [ "THlib::grain_b", "class_t_hlib_1_1grain__b.html", null ],
        [ "THlib::grain_c", "class_t_hlib_1_1grain__c.html", null ],
        [ "THlib::gun_bullet", "class_t_hlib_1_1gun__bullet.html", null ],
        [ "THlib::gun_bullet_void", "class_t_hlib_1_1gun__bullet__void.html", null ],
        [ "THlib::heart", "class_t_hlib_1_1heart.html", null ],
        [ "THlib::kite", "class_t_hlib_1_1kite.html", null ],
        [ "THlib::knife", "class_t_hlib_1_1knife.html", null ],
        [ "THlib::knife_b", "class_t_hlib_1_1knife__b.html", null ],
        [ "THlib::mildew", "class_t_hlib_1_1mildew.html", null ],
        [ "THlib::money", "class_t_hlib_1_1money.html", null ],
        [ "THlib::music", "class_t_hlib_1_1music.html", null ],
        [ "THlib::silence", "class_t_hlib_1_1silence.html", null ],
        [ "THlib::square", "class_t_hlib_1_1square.html", null ],
        [ "THlib::star_big", "class_t_hlib_1_1star__big.html", null ],
        [ "THlib::star_big_b", "class_t_hlib_1_1star__big__b.html", null ],
        [ "THlib::star_small", "class_t_hlib_1_1star__small.html", null ],
        [ "THlib::water_drop", "class_t_hlib_1_1water__drop.html", null ],
        [ "THlib::water_drop_dark", "class_t_hlib_1_1water__drop__dark.html", null ]
      ] ],
      [ "THlib::item", "class_t_hlib_1_1item.html", [
        [ "THlib::item_bomb", "class_t_hlib_1_1item__bomb.html", null ],
        [ "THlib::item_bombchip", "class_t_hlib_1_1item__bombchip.html", null ],
        [ "THlib::item_chip", "class_t_hlib_1_1item__chip.html", null ],
        [ "THlib::item_faith", "class_t_hlib_1_1item__faith.html", null ],
        [ "THlib::item_point", "class_t_hlib_1_1item__point.html", null ]
      ] ],
      [ "THlib::item_extend", "class_t_hlib_1_1item__extend.html", null ],
      [ "THlib::item_faith_minor", "class_t_hlib_1_1item__faith__minor.html", null ],
      [ "THlib::item_power", "class_t_hlib_1_1item__power.html", null ],
      [ "THlib::item_power_full", "class_t_hlib_1_1item__power__full.html", null ],
      [ "THlib::item_power_large", "class_t_hlib_1_1item__power__large.html", null ],
      [ "THlib::kill_timer", "class_t_hlib_1_1kill__timer.html", null ],
      [ "THlib::laser", "class_t_hlib_1_1laser.html", [
        [ "THlib::laser_death_ef", "class_t_hlib_1_1laser__death__ef.html", null ],
        [ "THlib::laser_shooter", "class_t_hlib_1_1laser__shooter.html", null ]
      ] ],
      [ "THlib::laser_bent", "class_t_hlib_1_1laser__bent.html", [
        [ "THlib::bent_laser_shooter", "class_t_hlib_1_1bent__laser__shooter.html", null ]
      ] ],
      [ "THlib::laser_bent2_death_ef", "class_t_hlib_1_1laser__bent2__death__ef.html", null ],
      [ "THlib::laser_bent_death_ef", "class_t_hlib_1_1laser__bent__death__ef.html", null ],
      [ "THlib::laser_bent_elec", "class_t_hlib_1_1laser__bent__elec.html", null ],
      [ "THlib::marisa_bullet_ef", "class_t_hlib_1_1marisa__bullet__ef.html", null ],
      [ "THlib::marisa_laser_hit", "class_t_hlib_1_1marisa__laser__hit.html", null ],
      [ "THlib::marisa_missile_ef", "class_t_hlib_1_1marisa__missile__ef.html", null ],
      [ "THlib::marisa_sp_ef", "class_t_hlib_1_1marisa__sp__ef.html", null ],
      [ "THlib::marisa_spark", "class_t_hlib_1_1marisa__spark.html", null ],
      [ "THlib::marisa_spark_wave", "class_t_hlib_1_1marisa__spark__wave.html", null ],
      [ "THlib::mask_fader", "class_t_hlib_1_1mask__fader.html", null ],
      [ "THlib::particle_img", "class_t_hlib_1_1particle__img.html", null ],
      [ "THlib::ParticleKepper", "class_t_hlib_1_1_particle_kepper.html", null ],
      [ "THlib::player_bullet_hide", "class_t_hlib_1_1player__bullet__hide.html", null ],
      [ "THlib::player_bullet_straight", "class_t_hlib_1_1player__bullet__straight.html", [
        [ "THlib::marisa_bullet", "class_t_hlib_1_1marisa__bullet.html", null ],
        [ "THlib::marisa_missile", "class_t_hlib_1_1marisa__missile.html", null ],
        [ "THlib::reimu_bullet_blue", "class_t_hlib_1_1reimu__bullet__blue.html", null ],
        [ "THlib::reimu_bullet_orange", "class_t_hlib_1_1reimu__bullet__orange.html", null ],
        [ "THlib::reimu_bullet_red", "class_t_hlib_1_1reimu__bullet__red.html", null ]
      ] ],
      [ "THlib::player_bullet_trail", "class_t_hlib_1_1player__bullet__trail.html", [
        [ "THlib::reimu_sp_ef", "class_t_hlib_1_1reimu__sp__ef.html", null ]
      ] ],
      [ "THlib::player_class", "class_t_hlib_1_1player__class.html", [
        [ "THlib::marisa_player", "class_t_hlib_1_1marisa__player.html", null ],
        [ "THlib::reimu_player", "class_t_hlib_1_1reimu__player.html", null ]
      ] ],
      [ "THlib::player_death_ef", "class_t_hlib_1_1player__death__ef.html", null ],
      [ "THlib::player_spell_mask", "class_t_hlib_1_1player__spell__mask.html", null ],
      [ "THlib::rebounder", "class_t_hlib_1_1rebounder.html", null ],
      [ "THlib::reimu_bullet_blue_ef", "class_t_hlib_1_1reimu__bullet__blue__ef.html", null ],
      [ "THlib::reimu_bullet_ef", "class_t_hlib_1_1reimu__bullet__ef.html", null ],
      [ "THlib::reimu_bullet_orange_ef", "class_t_hlib_1_1reimu__bullet__orange__ef.html", null ],
      [ "THlib::reimu_bullet_orange_ef2", "class_t_hlib_1_1reimu__bullet__orange__ef2.html", null ],
      [ "THlib::reimu_bullet_red_ef", "class_t_hlib_1_1reimu__bullet__red__ef.html", null ],
      [ "THlib::reimu_kekkai", "class_t_hlib_1_1reimu__kekkai.html", null ],
      [ "THlib::reimu_sp_ef1", "class_t_hlib_1_1reimu__sp__ef1.html", null ],
      [ "THlib::reimu_sp_ef2", "class_t_hlib_1_1reimu__sp__ef2.html", null ],
      [ "THlib::RenderObject", "class_t_hlib_1_1_render_object.html", null ],
      [ "THlib::replay_loader", "class_t_hlib_1_1replay__loader.html", null ],
      [ "THlib::replay_saver", "class_t_hlib_1_1replay__saver.html", null ],
      [ "THlib::sc_pr_menu", "class_t_hlib_1_1sc__pr__menu.html", null ],
      [ "THlib::shaker_maker", "class_t_hlib_1_1shaker__maker.html", null ],
      [ "THlib::shutter", "class_t_hlib_1_1shutter.html", null ],
      [ "THlib::simple_image", "class_t_hlib_1_1simple__image.html", null ],
      [ "THlib::simple_menu", "class_t_hlib_1_1simple__menu.html", null ],
      [ "THlib::smear", "class_t_hlib_1_1smear.html", null ],
      [ "THlib::spell_card_ef", "class_t_hlib_1_1spell__card__ef.html", null ],
      [ "THlib::tasker", "class_t_hlib_1_1tasker.html", null ]
    ] ],
    [ "THlib::ext::pause", "class_t_hlib_1_1ext_1_1pause.html", null ],
    [ "THlib::player_list", "class_t_hlib_1_1player__list.html", null ],
    [ "THlib::Queue", "class_t_hlib_1_1_queue.html", null ],
    [ "THlib::ext::Replay", "class_t_hlib_1_1ext_1_1_replay.html", null ],
    [ "THlib::archimedes::rotation", "class_t_hlib_1_1archimedes_1_1rotation.html", null ],
    [ "stage", null, [
      [ "THlib::debugger::stage_init", "class_t_hlib_1_1debugger_1_1stage__init.html", null ],
      [ "THlib::scdebugger::stage_init", "class_t_hlib_1_1scdebugger_1_1stage__init.html", null ]
    ] ],
    [ "string", "classstring.html", null ],
    [ "table", "classtable.html", null ],
    [ "task", "classtask.html", null ],
    [ "thread", "classthread.html", null ],
    [ "THlib::ui", "class_t_hlib_1_1ui.html", null ],
    [ "userdata", "classuserdata.html", null ]
];