LoadTTF('boss_name','THlib\\UI\\font\\default_ttf',20)
--LoadTTF('sc_name','THlib\\UI\\font\\default_ttf',20)
LoadTTF('sc_name','THlib\\UI\\font\\syst_heavy.otf',26)
LoadTTF('sc_pr','THlib\\UI\\font\\default_ttf',30)
LoadTTF('dialog','THlib\\UI\\font\\default_ttf',30)
LoadTTF('menuttf','THlib\\UI\\font\\default_ttf',20)

LoadFont('score','THlib\\UI\\font\\score_new.fnt',false)
LoadFont('item','THlib\\UI\\font\\item.fnt',true)
LoadFont('menu','THlib\\UI\\font\\menu.fnt',false)
LoadFont('bonus','THlib\\UI\\font\\bonus.fnt',true)
LoadFont('score1','THlib\\UI\\font\\score_new.fnt',false)
LoadFont('score2','THlib\\UI\\font\\score_new.fnt',false)
LoadFont('score3','THlib\\UI\\font\\score_new_score.fnt',false)
LoadFont('time','THlib\\UI\\font\\score_new_score.fnt',true)
LoadFont('replay','THlib\\UI\\font\\replay.fnt',false)
